### ISSUE TITLE
Object reference not set to an instance of an object. While attempting to use on a server.

### ISSUE THREAD

**Issue by Sector47** [chatrat12/Terraria3D#23]
Full error
Object reference not set to an instance of an object.
   at Terraria3D.Screen.get_Width()
   at Terraria3D.RTManager.UpdateDimensions()
   at Terraria3D.RTManager.Load()
   at Terraria3D.Renderers.Load()
   at Terraria3D.Loading.Load(Terraria3D instance)
   at Terraria3D.Terraria3D.Load()
   at Terraria.ModLoader.ModLoader.do_Load(Object threadContext)

Also if attempting to host a server from in game instead of through tmodloader it hangs on "starting server"

Same error with only Terrariahooks and Terraria 3d mods enabled

**Comment by prgmatic** [comment]
I have not tried to join a server, I'll get around to looking into it :D

**Comment by prgmatic** [comment]
Also, thank you for the report :)

**Comment by prgmatic** [comment]
Not sure if there is a way to stop it getting unloaded when joining a server that does not have it :\

**Comment by prgmatic** [comment]
Figured it out. `side = Client` in `build.txt` :D
